# Generated by Django 2.2 on 2020-06-15 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phoneNum', models.CharField(max_length=12)),
                ('facebookURL', models.URLField()),
                ('instagramURL', models.URLField()),
                ('youtubeURL', models.URLField()),
            ],
        ),
    ]
