# Generated by Django 2.2 on 2020-06-16 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20200615_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
